### ISSUE TITLE
Data Privacy Policy

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#103]
We need a clear and well advertised data privacy statement that authors and reviewers consent to.
- When or for what would we need ethics approval?

**Comment by annakrystalli** [comment]
Specialist Research Ethics Guidance Paper at TUoS
[PRINCIPLES OF ANONYMITY, CONFIDENTIALITY AND DATA PROTECTION](https://www.sheffield.ac.uk/polopoly_fs/1.724754!/file/SGREP-Anonymity-Confidentiality-DataProtection.pdf)

**Comment by annakrystalli** [comment]
[TUoS GDPR and data protection](https://www.sheffield.ac.uk/govern/data-protection#:~:text=The%20University%20Data%20Protection%20Officer,The%20project%20sponsor)

**Comment by annakrystalli** [comment]
This looks like a great resource: https://www.shu.ac.uk/about-this-website/privacy-policy/privacy-notices/privacy-notice-for-research

**Comment by DanielaGawehns** [comment]
My understanding: 
There are two things: 
A) How we treat privacy sensitive data (names, email addresses, phone numbers) and 
B) How we treat data that is collected and created during reprohacks/while interacting with the website. 

A is "easy", I feel, we should be able to use any GDPR template, fill in which data is stored and make sure that people can get their personal removed from the database

B is a little more intrecate. There is the question of anonymizing (what part of the data/how?) and how to ensure that people can get their data removed from the research data if they want to have it removed. I suggest a button that people click when handing in a feedback form and when sending in an article. And a phrase along the lines: "If you want to have your data removed from the research database, send us an email. We will ensure removal of all datapoints that are related to your person. We cannot guarantee to remove your data from already summarized and processed output." I came up with the second sentence thinking that that would ensure that processed/summarized/averaged data that is already published will need to be re-written?? Or is that too much of the good?

**Comment by DanielaGawehns** [comment]
Regarding B) there is also the question of informed consent. How do we phrase a consent that is open enough but at the same time specific enough?

**Comment by annakrystalli** [comment]
Agreed! Let's discuss today
