### ISSUE TITLE
Is password change URL correct?

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#123]
Is this where password change should be redirecting to for a given user?

![image](https://user-images.githubusercontent.com/5583057/134548306-56025890-b9c2-4c88-b950-aa8e589f8918.png)

**Comment by twinkarma** [comment]
It seemed like it was the original intention to do this, I just hooked it up to make the links work (or maybe the custom page just wasn't implemented in the first place) I can create an integrated password change form if you want.

**Comment by annakrystalli** [comment]
Yeah I'd prefer the interface to be consistent throughout the site. I think all the necessary templates are already in the `account` folder.

Perhaps we could sort #122 at the same time?
