### ISSUE TITLE
Populate the database with data

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#13]
- [ ] Production database needs to be populated with data from googlesheets. Shared already

- [ ] Would dev database be better with some dummy data?

**Comment by rgaiacs** [comment]
In Django language, we call it fixtures: https://docs.djangoproject.com/en/3.0/ref/django-admin/#what-s-a-fixture

> The most straightforward way of creating a fixture if you’ve already got some data is to use the `manage.py dumpdata` command.

And users can lead the "dummy" data with

```
django-admin loaddata mydata.json
```

**Comment by annakrystalli** [comment]
Thanks for the info @rgaiacs !!

**Comment by annakrystalli** [comment]
Emailed links to paper and feedback data. Here's the event data: https://github.com/reprohack/reprohack-hq/blob/master/data/event-log.csv

**Comment by annakrystalli** [comment]
### Data ranked in order of importance:
- [ ] Paper list 
- [ ] Event list
- [ ] Feedback data

Paper list & Feedback need placeholder accounts that users confirm after being sent an email
