### ISSUE TITLE
First name & Last name should be required on user model.

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#137]
Currently first name & Last name are not required on user model. They should however be.

Also, I'm having trouble understanding how to edit or how the model stores info as there's only a single name field in the custom user model: https://github.com/reprohack/reprohack_site/blob/88939f80cf9684b9a5463a0f4f712d6819a661b2/reprohack_hub/models.py#L75

Yet, in the signup form, there is a `first_name` and `last_name` field. Is there an extra filed in the model which we are not collecting while we're exposing default fields of the base user model in the forms? Is it a case of creating `first_name` and `last_name` fields in the custom user model (as you did with the `email` field? https://github.com/reprohack/reprohack_site/blob/88939f80cf9684b9a5463a0f4f712d6819a661b2/reprohack_hub/models.py#L76) and setting those as mandatory?

![image](https://user-images.githubusercontent.com/5583057/135713912-0fbb3540-cbb6-4788-a735-82541fac50e5.png)

**Comment by annakrystalli** [comment]
Quick question for you @twinkarma 👆

**Comment by twinkarma** [comment]
In the default User model there's actually a `first_name` and `last_name` field, so the `name` field is not being used at the moment. 

Was there a decision to change from this firstname lastname split to just a name field? If so then we can just change it to a single `name` field with a description of `Full name` or something like that? e.g.:

![image](https://user-images.githubusercontent.com/11231792/135933216-79977a21-0502-4995-a023-3973a3b8af6f.png)

**Comment by annakrystalli** [comment]
The reason I opted for splitting is so we can address emails to `first_name` which is a bit more informal. 

However, on looking at the advise for [internationalising name fields on forms ](https://www.w3.org/International/questions/qa-personal-names#splitting), I think my preferred approach would  be a `full_name` field followed by a `preferred_name` in which we ask users how they would like us to refer to them, e.g in emails, like so:
![image](https://user-images.githubusercontent.com/5583057/135937059-983471e9-7f3d-4854-b9fe-4ce0bc6b1e33.png)


We'll also need to update the `user_profile` to use `full_name` and the review email text to use `preferred_name`.

**Comment by twinkarma** [comment]
I've added full_name and preferred_name in  reprohack/reprohack_site@350b3d57b105f4f7512c35b8a0a93f548a0799dd 

I'll let you modify the e-mail templates yourself but just to be aware, you won't be able to access the user's name in the account related templates as the user is not actually logged in (so you can't do `{{ user.username }}`. You'd have to override allauth's builtin views but they will take time to implement and test.

When logged in, both full name and username is shown in the navbar: 

![image](https://user-images.githubusercontent.com/11231792/136047829-10effe42-382c-4d59-ad41-81401f1ab68c.png)

And there's the user detail change form:
![image](https://user-images.githubusercontent.com/11231792/136051695-7619eee5-b457-4b08-854e-8c138466655a.png)

And the signup form:
![image](https://user-images.githubusercontent.com/11231792/136051825-d6796adf-c784-4d58-a54a-a6beb0f21990.png)
