### ISSUE TITLE
Additional emails

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#164]
We should have a minimum of 2 more emails for people to contact us through:

- `reprohack-team@...`: to go to the core team, to replace `reprohack-team@gmail`
- `reprohack-coc@...`: to go to the COC committee

Are we OK with having `@sheffield.ac.uk` as the domain or should we try and get `reprohack.org` addresses? Although the `reprohack.org` looks better, it will cost (well we do have funds and it's only $24 a year) and may need extra time to set up. 

What do you think ladies think?

**Comment by LindaNab** [comment]
Agreed that @reprohack.org is nicer. Shouldn't we make it team@reprohack.org and coc@reprohack.org (or something like that) to avoid having 'reprohack' twice?  
and @DanielaGawehns' question: a rotating system is a good idea.

**Comment by annakrystalli** [comment]
Emails now created and TUoS accounts created for @LindaNab  & @DanielaGawehns and assigned as delegates.
