### ISSUE TITLE
Dockerzie

### ISSUE THREAD

**Issue by JamesVStone** [reprohack/reprohack_site#17]
- [x] Add Dockerfile
- [x] Add support for volumes (SQLite only)
- [x] Add docker compose
- [x] Add full-scale database

**Comment by JamesVStone** [comment]
@annakrystalli could this be added to the 'website launch' project

**Comment by annakrystalli** [comment]
Sure thing! Thanks for all your work so far!

**Comment by annakrystalli** [comment]
BTW, I'm guessing this issue is now complete right? Should I close it?
