### ISSUE TITLE
Bug: Reviews page shows 3 pages, each showing the same 3 reviews

### ISSUE THREAD

**Issue by sjvrijn** [reprohack/reprohack_site#190]
The reviews page https://www.reohack.org/review lists the 3 most recent reviews (as of right now at least), and shows "Previous [1] 2 3 Next" at the bottom of the page. However, when selecting page 2 and 3, the same 3 reviews are listed. I.e.:
* https://www.reprohack.org/review/?page=1
* https://www.reprohack.org/review/?page=2
* https://www.reprohack.org/review/?page=3

All show the same content

OS: Windows 10, both on Firefox 94.0.1 and Chrome 95.0.4638.69

**Comment by ellessenne** [comment]
I noticed the same (Safari 15.1, macOS 11.6.1)!

I am attaching some screenshots, see e.g. page 1:

![Screenshot 2021-11-18 at 5 56 51 PM](https://user-images.githubusercontent.com/10330005/142461695-9111c0b9-e533-484a-bdc4-4421c35acd46.png)

Page 2:

![Screenshot 2021-11-18 at 5 56 59 PM](https://user-images.githubusercontent.com/10330005/142461705-aae84cb3-a2bd-4ad3-886d-cb7e2bbd6da1.png)

**Comment by twinkarma** [comment]
For the pagination to work properly, the `get_queryset()` function has to be added to the `ReviewList` view (see `PaperList` class). It's the result of the `get_queryset()` function that paginator uses to do the pagination.

I can fix this for you later in the afternoon.

**Comment by annakrystalli** [comment]
Thanks @twinkarma that would be great!
