### ISSUE TITLE
Public Review Icon tooltip says 'Paper'

### ISSUE THREAD

**Issue by sjvrijn** [reprohack/reprohack_site#193]
When viewing the Reviews page, the icon indicating that a review is public has a tooltip `Paper is public`, see below.

![reprohub_paper_is_public](https://user-images.githubusercontent.com/8833517/142743575-95393b2d-8838-4f19-a4df-712fb8f73670.PNG)

OS: Windows 10, browser Chrome 96.0.4664.45 and Firefox 94.0.1

**Comment by annakrystalli** [comment]
Sorted in #197
