### ISSUE TITLE
Develop Review Report form

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#2]
* [x] `reproducibility_description` should be a markdown field
* [x] Review view permssion
  * [x] Author can make reviews public or not - warning that reviews will be public
  * [x] User can make reviews public or not
  * [x] Reviews become public if both Author and User allows it
* [ ] send email once review's done
  * Email template created in markdown
  * Use private gmail
* [ ] Enable discussion under review (use some kind of service?)

**Comment by annakrystalli** [comment]
The basis of this form can be the google form we have been using so far: https://github.com/reprohack/reprohack_site

**Comment by griff-rees** [comment]
Is this the latest version of the form to start with: https://docs.google.com/forms/d/e/1FAIpQLSesByo93VRId3xD7EgiQFDW9ep_14tkyuZUm_VCVxXeDexKGw/viewform

**Comment by annakrystalli** [comment]
No, it's the one in the comment above 👆

**Comment by griff-rees** [comment]
Cool thanks. First glance suggests this requires keys for

- *participant*: I guess with a `participant` (or similar) level permissions for the user model?
- *paper*: formatted to displaying the title following the list of 37 in the example

**Comment by annakrystalli** [comment]
Yes. Those IDs are present in the User model (user name for participants) and paper model (paper title). As I mentioned, participants might submit reviews as groups so that field will need to be a one to many field or perhaps a review group model would work in the participant field.

**Comment by griff-rees** [comment]
The individual vs group options are a bit tricky. I would have thought the user would be simply who's logged in filling the form in with an *optional* group option. The user would not show up on the form, that would be inferred by who is currently logged in. That would potentially imply 3 keys:

- user
- group
- paper

**Comment by griff-rees** [comment]
That would also require an additional group model, which could be part of the same form but that might be too tricky to directly integrate and may need a separate form.

**Comment by annakrystalli** [comment]
Radio button widgets: https://docs.djangoproject.com/en/3.0/ref/forms/widgets/

**Comment by griff-rees** [comment]
Hey. Mostly finished the radio form bit but it looks like we need a default value after all. Think I'll go back to 5 for the moment.

![Screenshot 2020-08-11 at 18 38 47](https://user-images.githubusercontent.com/60181741/89930187-3f674800-dc02-11ea-87cb-b9131166ecc0.png)

**Comment by griff-rees** [comment]
![Screenshot 2020-08-11 at 18 53 34](https://user-images.githubusercontent.com/60181741/89931450-0e881280-dc04-11ea-8be2-b43b7d55cef0.png)

**Comment by griff-rees** [comment]
We could try an option where nothing is selected initially, but I think that might have to hide the default option in `css` or `javascript`, don't think that's a possibility by default for required fields.
