### ISSUE TITLE
Paper Submission "Public Reviews - Text"

### ISSUE THREAD

**Issue by DanielaGawehns** [reprohack/reprohack_site#200]
Hi, 
it says "Only reviews that have also been set to public by reviewers will be visible to other signed in users" on the form for paper submission. But didnt we say that "Only reviews that have also been set to public by reviewers will be visible to **everyone** visiting the reprohack hub website"?

**Comment by DanielaGawehns** [comment]
Same on the page "Submit Review"

**Comment by annakrystalli** [comment]
Which page do you mean with 'Submit review?' https://www.reprohack.org/review/new ? As this doesn't mentioned signed in users. Is there another place I need to correct?

**Comment by DanielaGawehns** [comment]
Nope, you are right, I didnt read the text on https://www.reprohack.org/review/new correctly!
