### ISSUE TITLE
Tag "A" becomes "[<Tag: A]" after editing submitted paper

### ISSUE THREAD

**Issue by SamCH93** [reprohack/reprohack_site#218]
Hi,

I submitted a paper and wanted to make some changes after the submission. 
It seems that after making changes, a previously inserted tag, for example, "A" becomes "[<Tag: A>". The tag can be changed back manually. I see that there are many paper with tags of this form in the database. Not a huge issue but wanted to let you know :)

**Comment by annakrystalli** [comment]
Thanks @SamCH93 !

@twinkarma i think this may have started happening when we fixed the last bug with the tags. Any ideas how to stop this behaviour?

**Comment by annakrystalli** [comment]
Indeed this seems to be triggered when the form validator flags some other issue. When the form reloads, the tags are refreshed in their html form

**Comment by annakrystalli** [comment]
So it seems that after saving, the tag field becomes a type of list that behaves differently with `.join` and also doesn't evaluate to `true` with `if value is list` but rather with `type(value) == list`.  So I'm adding another condition to handle.
