### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by griff-rees** [reprohack/reprohack_site#32]
Hey @annakrystalli: I think the rest of my database questions are mostly sorted now, but the one I meant to ask is whether it makes sense to extract out the location section for events as a venue so they can be re-used. So the `location` field would be a foreign key to a table like this. We can also add an extra text field for stuff that might change from event to event:

```python
class Venue(gismodels.Model):

    name = models.CharField(max_length=200)
    address1 = models.CharField(max_length=200)
    address2 = models.CharField(max_length=200)
    city = models.CharField(max_length=60)
    postcode = models.CharField(max_length=15)
    country = models.CharField(max_length=60)
    geom = Point()
```

**Comment by annakrystalli** [comment]
Personally I don't think they will be reused that often, but I think it's a good idea to have a separate venue model. 

We should however keep a location field (but maybe rename or provide extra clarification on the front end?) as that's where details of a specific room / location within a venue are supposed to go.

This actually makes me think of an additional option that we should be able to cater to, and that's a remote version.  So I wonder if having a remote toggle that only has an optional call link field would be good. This is probably something we will need but might be something we need to sort out ourselves given the time restriction so I'll go ahead and open another issue for it. 

If you have a simple solution that might be clunky but that we could make slicker later feel free to add it now, otherwise just leave it and we'll pick it up later.

**Comment by annakrystalli** [comment]
I've opened the new issue(#33 ) . I have tagged it with N8 sprint tag but feel free to ignore it given the time restrictions.

**Comment by griff-rees** [comment]
Figured it was easiest to answer this by showing you the change to other model. If this is generic enough to get started.

```python
 class Event(gismodels.Model):

    """An event to organise reproducing Paper results.

    """
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    host = models.CharField(max_length=200)
    title = models.CharField(_('Event Title'), max_length=200)
    # time
    date = models.DateField(default=date.today)
    start_time = models.DateTimeField(default=timezone.now().replace(minute=00, hour=10))
    end_time = models.DateTimeField(default=timezone.now().replace(minute=00, hour=16))
    # location
    location = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True)
    location_description = models.CharField(_('Eg: Room #'), max_length=300)
```

**Comment by griff-rees** [comment]
Oh ha sorry, just finished previewing that and hit submit, sorry!

**Comment by annakrystalli** [comment]
No worries! Can we call the location field `venue` instead? just so it ties in nicely with the name of the model?

**Comment by annakrystalli** [comment]
So have the two fields be 

- `venue`
- `location_in_venue`

I think they are nicely self descriptive. 

I see what you mean about the separation of the location within the venue from the venue details (so venue details maybe could be reused). But I think that might be more complicated than necessary. Ie how will we allow the user to reuse those details?  

For me the venue and location within venue should all be part of the same form so to reuse previous venues we would have to add an additional dropdown menu for them, no?  Given how rarely I think such a feature might be used and how minimal the data is, while a cool idea, I don't feel its worth the complication. Especially given the forms already bring back up text you've previously entered.

So to conclude, I like the idea of a separate venue model but I'd like everything about the venue (including location within venue) to be in the venue model and a separate instance entered for each event.

**Comment by griff-rees** [comment]
Heh so now going back and forth between the tickets (see  #33), didn't see your replies! Right I've got a meeting soon but I think we mostly agree on basic stuff, happy to change the names.

**Comment by annakrystalli** [comment]
Cool, I've got some extra comments in #33, could you just confirm here or there with a 👍 that you've seen them please?

**Comment by griff-rees** [comment]
@annakrystalli sorry connection's spotty and needed to finish a call.

First: to sort the question of how the data is stored, an advantage of `Postgresql` is documented here so an extra time zone field shouldn't be needed. You should be able to see that in the [configuration](https://github.com/reprohack/reprohack_site/blob/dev/config/settings/base.py#L3):

https://docs.djangoproject.com/en/3.0/topics/i18n/timezones/#database

If you're happy with that method of storage, then we can shift to the way the option is presented in the form. Your link to the dropdown option is useful, thanks for that. I'll try that when I get to the form, though there are some comments on that response that may involve some complications. Will figure when I get there.

I meant to include a descriptive option, so here's another draft of the models to clarify. Only other suggestion is maybe `venue_detail` rather than `location_in_venue` as that's a bit more generic (say, 'Page person X on arrival' etc.):

```python
class Event(gismodels.Model):

    """An event to organise reproducing Paper results."""

    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    host = models.CharField(max_length=200)
    title = models.CharField(_('Event Title'), max_length=200)
    start_time = models.DateTimeField(default=timezone.now().replace(minute=00, hour=10))
    end_time = models.DateTimeField(default=timezone.now().replace(minute=00, hour=16))
    # location
    venue = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True)
    location_in_venue = models.CharField(_('Eg: Room #'), max_length=300)
    submission_date = models.DateTimeField(default=timezone.now)
    registration_url = models.URLField()
    # remote = models.BooleanField(default=False)

class Venue(models.Model):

    """Venue for Events."""

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    address1 = models.CharField(max_length=200)
    address2 = models.CharField(max_length=200)
    city = models.CharField(max_length=60)
    postcode = models.CharField(max_length=15)
    country = models.CharField(max_length=60)
    geom = Point()
```

**Comment by annakrystalli** [comment]
Re: timezone, happy with how `postgresql` stores it with UTC being my preference. My reasoning for being able to change is it that I might be submitting an event while in the UK that I'm actually going to run say in the Netherlands. In that case I would want to be able to specify that the advertised times are in the Netherlands timezone. To be fair this could probably be determined from the venue address automatically but wouldn't be the case in a remote setting.


Re: `venue_detail`, sure that works fine.

**Comment by griff-rees** [comment]
@annakrystalli I *think* that's edge cases covered now. Thoughts appreciated.

**Comment by annakrystalli** [comment]
Also, I don't think we need a `name` field in the venue model.

**Comment by annakrystalli** [comment]
And we don't need a venue description in the event model

**Comment by griff-rees** [comment]
The `name` field presents what the venue is (say in a dropdown menu), which I think is different from `detail` (for example: room numbers can be ambiguous across buildings). We could just have `address1` as the name if you prefer? It's mainly a question of what to use in `def __str__(self)`.

The `venue_description` is meant to cover cases where stuff varies per event at the same venue. Eg: if arrival/registration plans are different but the venue is the same.

**Comment by annakrystalli** [comment]
Please read my full comments. I don't want this behaviour

> So have the two fields be 
> 
> 
> 
> - `venue`
> 
> - `location_in_venue`
> 
> 
> 
> I think they are nicely self descriptive. 
> 
> 
> 
> I see what you mean about the separation of the location within the venue from the venue details (so venue details maybe could be reused). But I think that might be more complicated than necessary. Ie how will we allow the user to reuse those details?  
> 
> 
> 
> For me the venue and location within venue should all be part of the same **form** (ie user facing) so to reuse previous venues we would have to add an additional dropdown menu for them, no?  Given how rarely I think such a feature might be used and how minimal the data is, while a cool idea, I don't feel its worth the complication. Especially given the forms already bring back up text you've previously entered.
> 
> 
> 
> So to conclude, I like the idea of a separate venue model but I'd like everything about the venue (including location within venue) to be in the venue model and a separate instance entered for each event.

**Comment by annakrystalli** [comment]
Also, it just occurred to me, should the Venue model be the `gismodels.Model`?

**Comment by griff-rees** [comment]
Yes you're right, the `Venue` should be the `gismodel`. Apologies.

I believe the `timezone` information is included in the `DateTimeField` already in part because `USE_TZ = True` in `settings` (hence the link above) but I can see advantages in storing that information more explicitly. I'm not sure if that's a default option in django models but I can look that up. We could try a choice filed like the one suggested. I think that's a more generic problem that's separate to the `Venue` model so perhaps that fits another ticket.

I think I misunderstood the *separate instance entered for each event* portion of your message. Rereading suggests it doesn't make sense to have a separate table then. Apologies for the suggestion.

**Comment by annakrystalli** [comment]
No worries. Sorry if I wasn't clear.
