### ISSUE TITLE
Missing staticfiles manifest entry for 'reprohack/leaflet/leaflet.awesome-markers.css'

### ISSUE THREAD

**Issue by willfurnass** [reprohack/reprohack_site#53]
New sub-Issue of #37 (as of e977c45d8b0154beb78072b0c3e1c291064f94b1 on the dev branch):

```
django_1        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 423, in stored_name
django_1        |     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
django_1        | ValueError: Missing staticfiles manifest entry for 'reprohack/leaflet/leaflet.awesome-markers.css'
```

**Comment by willfurnass** [comment]
Trying adding leaflet.awesome-markers 2.0.5 via [package.json](package.json) to see if that fixes this...

**Comment by willfurnass** [comment]
@annakrystalli @griff-rees The above resulted in npm sticking the missing file in `node_modules/leaflet.awesome-markers/` beneath the Django root.  Does this dir need appending to `STATICFILES_DIRS` in `config/settings/base.py`?

**Comment by griff-rees** [comment]
Sorted with in 625d65afa8998cba2006113ec947a19bfaac2897. Ideally we do that for the rest of the `javascript` dependencies...
