### ISSUE TITLE
First time instructions

### ISSUE THREAD

**Issue by cmoralesmx** [reprohack/reprohack_site#56]
I am following the [instructions](https://github.com/reprohack/reprohack_site) to start working on the site for the first time.
After cloning the repository and installing docker-compose, I proceeded directly to:
> If this is your first time, you need to create the database:
> `$ docker-compose exec django python manage.py migrate`

I assume this must be executed from the project's root directory, am I right?
However, if I do so, I get the following error message
```bash
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

The only directory containing a `docker-compose.yml` file is `./backup/`

So, I tried executing the same command from `./backup` but I got the same error. Then, I tried doing `$ docker-compose up` from `./backup` and finally saw some progress which ended with the following error  

```
Creating network "backup_default" with the default driver
Creating volume "backup_db_data" with default driver
Pulling db (mariadb:10.5-bionic)...
10.5-bionic: Pulling from library/mariadb
23884877105a: Pull complete
bc38caa0f5b9: Pull complete
2910811b6c42: Pull complete
36505266dcc6: Pull complete
e69dcc78e96e: Pull complete
222f44c5392d: Pull complete
efc64ea97b9c: Pull complete
9912a149de6b: Pull complete
7ef6cf5b5697: Pull complete
8a05be3688e0: Pull complete
855d0aa8c6bf: Pull complete
8662ea944449: Pull complete
212f95fccfdc: Pull complete
Digest: sha256:2d2e5e513798d82cc538f83f2b38c9af5adeb58ec7c81290667d6b3a1fa3edc5
Status: Downloaded newer image for mariadb:10.5-bionic
Building django
Step 1/7 : FROM python:3 as development
3: Pulling from library/python
57df1a1f1ad8: Pull complete
71e126169501: Pull complete
1af28a55c3f3: Pull complete
03f1c9932170: Pull complete
65b3db15f518: Pull complete
3e3b8947ed83: Pull complete
f156949921a1: Pull complete
1c1931013093: Pull complete
51fff639b6bf: Pull complete
Digest: sha256:1a126607adde46a706e76357c910f36b9f5529fb575d4d86a639a4997daceba7
Status: Downloaded newer image for python:3
 ---> bbf31371d67d
Step 2/7 : ENV PYTHONBUFFERED 1
 ---> Running in 704a718f21ea
Removing intermediate container 704a718f21ea
 ---> 6a309df21ff2
Step 3/7 : WORKDIR /opt/reprohack
 ---> Running in 4721d31e7099
Removing intermediate container 4721d31e7099
 ---> 02c41e34b338
Step 4/7 : COPY requirements.txt ./
ERROR: Service 'django' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder937372890/requirements.txt: no such file or directory
```

If I try to create the database at this point, I get a new error:

```bash
ERROR: No container found for django_1
```

Would you please help me identify what am I doing wrong? Otherwise, I guess the instructions may need to be updated to reflect changes to the project structure.

I am running Ubuntu 20.04 with Docker version 19.03.8, docker-compose version 1.25.0

**Comment by annakrystalli** [comment]
Hello @cmoralesmx !! And many thanks for your interest in this Project. We currently have a developer (@griff-rees) working on a major refactoring of the project and there are likely to be many bugs still. We are working on them and expecting to make a big push to `master` in the next couple of days. This might fix some of the issues you are having!

So, would you mind if I just pinged you in this issue when that merge has been made? Then you can try again and of you are still having issues, we can try and help?

**Comment by griff-rees** [comment]
Hey @cmoralesmx! Thanks for the message and yes apologies the documentation has not been updated. We've significantly refactored the project via https://github.com/pydanny/cookiecutter-django and the old components are left in `backup`. To have a go at running locally with docker use `docker-compose -f local.yml build` then `docker-compose -f local.yml up`, probably safest from the `dev` branch at the moment. Will be updating the docs and merging to `master` once we've finished the migration, and yes it'd be great to have further contributions!

**Comment by cmoralesmx** [comment]
Thanks for both responses, and apologies for the wait, the past few days have been hectic. I am finally ready to contribute. I have been checking the open issues but I am not sure if there may be an area where more hands are needed. Any suggestions? I am more at ease with back-end development but I can adapt. Thanks
