### ISSUE TITLE
Production config: support Django's plain SMTP email backend (as an alternative to AnyMail/MailGun)

### ISSUE THREAD

**Issue by willfurnass** [reprohack/reprohack_site#58]
With the production docker-compose config it would be useful to be able to use a local SMTP server if available instead of AnyMail/MailGun.  This choice could be made by a sysadmin by assigning to various variables in Django's environment, which in turn could result in variables being set in Django's Python-based config.

**Comment by griff-rees** [comment]
There's more to test but the basic options should now be available. [Anymail](https://anymail.readthedocs.io/en/stable/) supports a [range of providers](https://anymail.readthedocs.io/en/stable/esps/), just [features MailGun in the documentation](https://anymail.readthedocs.io/en/stable/installation/#configuring-django-s-email-backend).
