### ISSUE TITLE
PostGIS Docker image: switch to using use official postgis images 

### ISSUE THREAD

**Issue by willfurnass** [reprohack/reprohack_site#61]
The one we're using at present has lots of known vulnerabilities in the OS packages; compare
```
sudo trivy image --severity HIGH,CRITICAL --ignore-unfixed mdillon/postgis:11-alpine
```
with 
```
sudo trivy image --severity HIGH,CRITICAL --ignore-unfixed docker pull postgis/postgis:11-2.5-alpine
sudo trivy image --severity HIGH,CRITICAL --ignore-unfixed docker pull postgis/postgis:11-3.0-alpine
```

See https://registry.hub.docker.com/r/postgis/postgis for more info on the official postgis images.

Could also use the opportunity to switch to PostgreSQL 12 or 13.

**Comment by griff-rees** [comment]
Hey I've got a potential fix: https://github.com/griff-rees/reprohack_site/commit/72cd3dc34bb815486ecae8f69ef5f200115c6f8b can set up a pull request if you like. I'm pretty sure this comes out of this issue: https://github.com/postgis/docker-postgis/issues/143

**Comment by griff-rees** [comment]
Just got it working on `PostgreSQL` 13. Might require an initial purge of previous volumes though: https://cookiecutter-django.readthedocs.io/en/latest/troubleshooting.html#docker-postgres-authentication-failed
