### ISSUE TITLE
Papers model additional features

### ISSUE THREAD

**Issue by twinkarma** [reprohack/reprohack_site#87]
* [x] Option to archive paper - Archived paper does not show up in future events for review
* [ ] Paper list show as accordian
  * Title & tags
* [ ] Paper list filtering
  * Papers by tags?
  * Papers by search?
  * Papers by events?
  * Language
  * Domain
  * What tools have been use
* [x] Paper list pagination

**Comment by annakrystalli** [comment]
Here's a nice recent example of a paperlist: http://shinyapps.sheffield.ac.uk/imperial-shef-reprohack

A nice option could be a navigable table with details like Title & tools used and when you click on an entry on a table a card like the one in the paperlist above

**Comment by twinkarma** [comment]
@annakrystalli I'd noticed that the Paper model doesn't currently have an 'author' field or that it's associated with any users of the system.

I propose we have an:
* `Authors` as just a text field, to list all the authors associated to the paper
* `Submitter` as a foreign key field, this associates to the actual user that's submitted the paper

Does this sound ok?

**Comment by annakrystalli** [comment]
Sounds sensible to me.
