### ISSUE TITLE
Add review counts and men repro score to paper list views

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#95]
Should be part of the paper model but only calculated when the paper list or individual view is called

**Comment by twinkarma** [comment]
@annakrystalli Is the repro score just the `reproducibility_rating` field in the review form or a combination of multiple ratings?

**Comment by annakrystalli** [comment]
Just the reproduction rating.

Also if there is no reviews for a given paper, this and the number of reviews should just not appear in the template. Like it appears here: http://shinyapps.sheffield.ac.uk/imperial-shef-reprohack/
